export const weatherTranslates: Record<string, string> = {
  //Principal
  Clouds: "Nubes",
  Clear: "Despejado",
  Snow: "Nieve",
  Rain: "Lluvia",
  Drizzle: "Llovizna",
  Thunderstorm: "Tormenta eléctrica",

  //Descripción
  "light thunderstorm": "tormenta eléctrica ligera",
  "thunderstorm with heavy rain": "tormenta eléctrica con lluvia intensa",
  "thunderstorm with rain": "tormenta eléctrica con lluvia",
  "thunderstorm with light rain": "tormenta eléctrica con lluvia ligera",
  thunderstorm: "tormenta eléctrica",
  "heavy thunderstorm": "tormenta eléctrica intensa",
  "ragged thunderstorm": "tormenta eléctrica irregular",
  "thunderstorm with light drizzle": "tormenta eléctrica con llovizna ligera",
  "thunderstorm with drizzle": "tormenta eléctrica con llovizna",
  "thunderstorm with heavy drizzle": "tormenta eléctrica con llovizna intensa",
  "light intensity drizzle": "llovizna de intensidad ligera",
  drizzle: "llovizna",
  "heavy intensity drizzle": "llovizna de intensidad fuerte",
  "light intensity drizzle rain": "lluvia con llovizna de intensidad ligera",
  "drizzle rain": "lluvia con llovizna",
  "heavy intensity drizzle rain": "lluvia con llovizna de intensidad fuerte",
  "shower rain and drizzle": "lluvia intensa y llovizna",
  "heavy shower rain and drizzle": "lluvia intensa y llovizna intensa",
  "shower drizzle": "llovizna intensa",
  "light rain": "lluvia ligera",
  "moderate rain": "lluvia moderada",
  "heavy intensity rain": "lluvia de intensidad fuerte",
  "very heavy rain": "lluvia muy fuerte",
  "extreme rain": "lluvia extrema",
  "freezing rain": "lluvia helada",
  "light intensity shower rain": "lluvia de ducha de intensidad ligera",
  "shower rain": "lluvia de ducha",
  "heavy intensity shower rain": "lluvia de ducha de intensidad fuerte",
  "ragged shower rain": "lluvia de ducha irregular",
  "light snow": "nieve ligera",
  snow: "nieve",
  "heavy snow": "nieve fuerte",
  sleet: "aguanieve",
  "light shower sleet": "aguanieve ligera",
  "shower sleet": "aguanieve de ducha",
  "light rain and snow": "lluvia y nieve ligera",
  "rain and snow": "lluvia y nieve",
  "light shower snow": "nieve de ducha ligera",
  "shower snow": "nieve de ducha",
  "heavy shower snow": "nieve de ducha fuerte",
  "clear sky": "cielo despejado",
  "few clouds": "pocas nubes",
  "scattered clouds": "nubes dispersas",
  "broken clouds": "nubes rotas",
  "overcast clouds": "cielo nublado",
};
